version: 2
project_name: gitlab-token-updater
before:
  hooks:
    - go mod tidy

builds:
  - main: main.go 
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X main.BuildHash={{.Commit}} -X main.Version={{.Version}}
    tags:
      - static_build

checksum:
  name_template: 'checksums.txt'

archives:
  - files:
      # Only include built binary in archive
      - 'none*'
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'