# host will be use default one to https://gitlab.com/
# token will set be provided use env variable (GL_RENEWER_TOKEN), see .gitlab-ci.yml for more detail

manage_tokens:
  - path: path/to/group
    type: group
    access_tokens:
      - name: api_automation
        hooks:
          - type: update_var
            args:
              path: path/to/another/subgroup
              type: group
              name: AUTOMATION_TOKEN

          - type: exec_cmd
            retry: 2
            args:
              path: ./scripts/update_secret_manager.sh

      - name: monitoring_purpose
        expiry_after_rotate: 3M

  - path: path/to/repo
    type: repository
    access_tokens:
      - name: TF IaC
        hooks:
          - type: update_var
            args:
              path: path/to/repo
              type: repository
              name: MR_COMMENTER_TOKEN

  - include: internal.yml